"""empty message

Revision ID: 14e7a9b4e00d
Revises: 2e5706473890
Create Date: 2015-08-22 21:20:26.931902

"""

# revision identifiers, used by Alembic.
revision = '14e7a9b4e00d'
down_revision = '2e5706473890'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ns_users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('ns_users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('ns_users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('ns_users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('ns_users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_users', 'name')
    op.drop_column('ns_users', 'member_since')
    op.drop_column('ns_users', 'location')
    op.drop_column('ns_users', 'last_seen')
    op.drop_column('ns_users', 'about_me')
    ### end Alembic commands ###
