"""empty message

Revision ID: 1d97cb5f4d6b
Revises: 565fd2919547
Create Date: 2015-08-23 22:43:37.550081

"""

# revision identifiers, used by Alembic.
revision = '1d97cb5f4d6b'
down_revision = '565fd2919547'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ns_follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('followed_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['ns_users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['ns_users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ns_follows')
    ### end Alembic commands ###
