"""empty message

Revision ID: 27bd8b77e70f
Revises: 2ec9b37a5c06
Create Date: 2015-08-25 01:27:22.695976

"""

# revision identifiers, used by Alembic.
revision = '27bd8b77e70f'
down_revision = '2ec9b37a5c06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
