"""empty message

Revision ID: 2c77ac1e890b
Revises: 27bd8b77e70f
Create Date: 2015-08-25 11:31:57.227741

"""

# revision identifiers, used by Alembic.
revision = '2c77ac1e890b'
down_revision = '27bd8b77e70f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ns_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_ns_roles_default', 'ns_roles', ['default'], unique=False)
    op.create_table('ns_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ns_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ns_users_email', 'ns_users', ['email'], unique=True)
    op.create_table('ns_follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('followed_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['ns_users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['ns_users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('ns_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['ns_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ns_posts_timestamp', 'ns_posts', ['timestamp'], unique=False)
    op.create_table('ns_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['ns_users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['ns_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ns_comments_timestamp', 'ns_comments', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ns_comments_timestamp', 'ns_comments')
    op.drop_table('ns_comments')
    op.drop_index('ix_ns_posts_timestamp', 'ns_posts')
    op.drop_table('ns_posts')
    op.drop_table('ns_follows')
    op.drop_index('ix_ns_users_email', 'ns_users')
    op.drop_table('ns_users')
    op.drop_index('ix_ns_roles_default', 'ns_roles')
    op.drop_table('ns_roles')
    ### end Alembic commands ###
