"""empty message

Revision ID: 4f0a4c7707dd
Revises: 14e7a9b4e00d
Create Date: 2015-08-23 09:59:05.853287

"""

# revision identifiers, used by Alembic.
revision = '4f0a4c7707dd'
down_revision = '14e7a9b4e00d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ns_users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_users', 'avatar_hash')
    ### end Alembic commands ###
