"""empty message

Revision ID: 565fd2919547
Revises: 2c27b48ead1b
Create Date: 2015-08-23 13:44:00.881134

"""

# revision identifiers, used by Alembic.
revision = '565fd2919547'
down_revision = '2c27b48ead1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ns_posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_posts', 'body_html')
    ### end Alembic commands ###
