"""empty message

Revision ID: 28b22595ff17
Revises: 2bd2b1bd2df7
Create Date: 2015-08-25 21:29:50.696034

"""

# revision identifiers, used by Alembic.
revision = '28b22595ff17'
down_revision = '2bd2b1bd2df7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ns_rooms', ['number'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ns_rooms')
    ### end Alembic commands ###
