"""empty message

Revision ID: 294245a20e30
Revises: 28b22595ff17
Create Date: 2015-08-26 11:44:53.708415

"""

# revision identifiers, used by Alembic.
revision = '294245a20e30'
down_revision = '28b22595ff17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ns_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('zipcode', sa.String(length=7), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ns_books_created_at', 'ns_books', ['created_at'], unique=False)
    op.create_index('ix_ns_rooms_created_at', 'ns_rooms', ['created_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ns_rooms_created_at', 'ns_rooms')
    op.drop_index('ix_ns_books_created_at', 'ns_books')
    op.drop_table('ns_profiles')
    ### end Alembic commands ###
