"""empty message

Revision ID: 2bd2b1bd2df7
Revises: 5232c99d9c34
Create Date: 2015-08-25 20:29:19.743056

"""

# revision identifiers, used by Alembic.
revision = '2bd2b1bd2df7'
down_revision = '5232c99d9c34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ns_rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ns_books',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('checkin_on', sa.Date(), nullable=True),
    sa.Column('checkout_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ns_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ns_room_books',
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('book_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['ns_books.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['ns_rooms.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ns_room_books')
    op.drop_table('ns_books')
    op.drop_table('ns_rooms')
    ### end Alembic commands ###
