"""empty message

Revision ID: 36f9ecf4eb3e
Revises: 4fa8ab177908
Create Date: 2015-08-26 21:02:45.808475

"""

# revision identifiers, used by Alembic.
revision = '36f9ecf4eb3e'
down_revision = '4fa8ab177908'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
