"""empty message

Revision ID: 3e2a2f79ec18
Revises: 48f70bbc0e5a
Create Date: 2015-09-09 19:29:46.919181

"""

# revision identifiers, used by Alembic.
revision = '3e2a2f79ec18'
down_revision = '48f70bbc0e5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ns_books_checkin_on', 'ns_books', ['checkin_on'], unique=False)
    op.create_index('ix_ns_books_checkout_on', 'ns_books', ['checkout_on'], unique=False)
    op.add_column('ns_rooms', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('ns_rooms', sa.Column('guests', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_rooms', 'guests')
    op.drop_column('ns_rooms', 'active')
    op.drop_index('ix_ns_books_checkout_on', 'ns_books')
    op.drop_index('ix_ns_books_checkin_on', 'ns_books')
    ### end Alembic commands ###
