"""empty message

Revision ID: 402d04eed399
Revises: 52083dce84f2
Create Date: 2015-08-26 11:57:49.076474

"""

# revision identifiers, used by Alembic.
revision = '402d04eed399'
down_revision = '52083dce84f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ns_profiles', sa.Column('user_id', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ns_profiles', 'user_id')
    ### end Alembic commands ###
