"""empty message

Revision ID: 46b66e67594
Revises: 36f9ecf4eb3e
Create Date: 2015-08-26 21:08:07.925135

"""

# revision identifiers, used by Alembic.
revision = '46b66e67594'
down_revision = '36f9ecf4eb3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
