"""empty message

Revision ID: 48f70bbc0e5a
Revises: 46b66e67594
Create Date: 2015-08-26 21:29:36.766212

"""

# revision identifiers, used by Alembic.
revision = '48f70bbc0e5a'
down_revision = '46b66e67594'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
