"""empty message

Revision ID: 4fa8ab177908
Revises: 402d04eed399
Create Date: 2015-08-26 18:30:01.854061

"""

# revision identifiers, used by Alembic.
revision = '4fa8ab177908'
down_revision = '402d04eed399'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
