"""empty message

Revision ID: 52083dce84f2
Revises: 294245a20e30
Create Date: 2015-08-26 11:55:14.438204

"""

# revision identifiers, used by Alembic.
revision = '52083dce84f2'
down_revision = '294245a20e30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
